### ISSUE TITLE
Cant interact with html map

### ISSUE THREAD

**Issue by alitarraf** [toddwschneider/nyc-motor-vehicle-collisions#1]
Hi Todd! 

I cant seem to get the html file render properly. I have followed the instructions in your read me and initiated the databases.
Also did not notice how you are creating the html file, can you point me to that code?

![image](https://user-images.githubusercontent.com/21084320/80110622-8bc14600-8587-11ea-8438-10a34c5cdbe7.png)

**Comment by toddwschneider** [comment]
@alitarraf it looks like you are trying to open the page as a local file. My guess is that your browser is blocking the https resources from loading because you have it opened as a file (`file://` instead of `http(s)://`). If you [run a local server](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server#Running_a_simple_local_HTTP_server) then it will hopefully work

There is no code to generate the html file, it's just a file. It's not minified or obfuscated so you should be able to look at the file itself in a text editor (or view source in your browser) to see all of the html, css, and javascript

I'm going to close this issue but lmk if you have more questions, thanks

**Comment by alitarraf** [comment]
Thanks for the follow up! I launched a server but I am still getting same results. I looked into the code, and noticed that the export_data.sql is running to generate the required csv file. 

I am pretty sure I am missing something in my setup. Any tips are appreciated.
![image](https://user-images.githubusercontent.com/21084320/80221611-3603a100-864e-11ea-8036-454c5e69bdb2.png)

**Comment by alitarraf** [comment]
Also running the export_data.sql to generate the csv file results in some errors below.
![image](https://user-images.githubusercontent.com/21084320/80232590-d44b3300-865d-11ea-8d03-dfe17b208f4e.png)

**Comment by toddwschneider** [comment]
@alitarraf it looks like the `export_data.sql` script is not running at all. Maybe you need to specify the database name in your `psql` command? Are you sure you've loaded the data correctly?

**Comment by alitarraf** [comment]
Todd, You were right, data was not being loaded. After messing around a bit with the raw data file (the export_data.sql was throwing out some errors) I got the export_data.sql to generate the nyc-motor-vehicle-collisions.csv data.
![image](https://user-images.githubusercontent.com/21084320/80377297-c38bfe80-88a3-11ea-8986-00dfcee75d11.png)

However, I still face the same problem where the map is not being generated. Note I added my mapbox api and i have the base url and data url edited.
![image](https://user-images.githubusercontent.com/21084320/80377662-41e8a080-88a4-11ea-8e81-b26f175b7a7c.png)

I have tried a deckgl example [here](https://github.com/visgl/deck.gl/tree/master/examples/get-started/pure-js/mapbox), and deckgl mapbox are working locally.

Do you have any advice on what should I look for to get the map to render?Not sure what am I missing...

**Comment by alitarraf** [comment]
Updates:
If I look at the existing working app on your website and I copy the collisions bundle to the exsiting html head:
```    <script src="https://cdn.toddwschneider.com/collisions/collisions-bundle.6.4.0.js"></script>```

The map renders and works well however with one issue:
-  the hexagon doesnt change size when zooming

I am thinking I might be missing some js library from the collisions bundle. Let me know if this helps clarify the issue further.

**Comment by toddwschneider** [comment]
@alitarraf I don't think you're missing anything, all js is included in that bundle file. The map file in this repo does not resize the hexagons on zoom. The resizing only happens in the preaggregated version of the map, which is not part of the repo

You can view the source on the preaggregated version here: https://toddwschneider.com/maps/nyc-motor-vehicle-collisions/preaggregated/

**Comment by alitarraf** [comment]
Thanks Todd, yes i noticed the adaptive hex function after review. Are there other scripts that are included in the bundle on the web page but not in the repo scripts ? 
This might explain why the map was not rendering without the bundle.

**Comment by toddwschneider** [comment]
Not that I'm aware of
